### ISSUE TITLE
20240501 작업 내용

### ISSUE THREAD

**Issue by URBAN-IA** [UPSTAGEAILAB-G2024/RE_DataEDA#1]

**Comment by developzest** [comment]
- EDA
   - 소득
   - 실업률
   - 유동인구

**Comment by developzest** [comment]
- 데이터 수집
  - https://github.com/UPSTAGEAILAB-G2024/developzest/issues/1

**Comment by developzest** [comment]
@Kerneld82 @jojaen @UBAILAB 참고 부탁드립니다 =)
